language: c
os:
  - linux
dist: focal
addons:
  apt:
    packages:
      - astyle
      - aspcud
      - libgnomecanvas2-dev
      - libgtk2.0-dev
      - libgtksourceview2.0-dev
      - graphviz

cache:
  directories:
    - $HOME/bin
    - $HOME/.opam

env:
  global:
    - WP_TIMEOUT=1
    - WP_PROCESSES=3

before_install:
  - sudo apt update -qq
  - which opam || (
      wget --quiet --no-clobber https://github.com/ocaml/opam/releases/download/2.0.7/opam-2.0.7-x86_64-linux -O $HOME/bin/opam &&
      chmod +x $HOME/bin/opam
    )
  - which cvc4 || (
      wget --quiet --no-clobber http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/cvc4-1.7-x86_64-linux-opt -O $HOME/bin/cvc4 &&
      chmod +x $HOME/bin/cvc4
    )
  - which z3 || (
      wget --quiet https://github.com/Z3Prover/z3/releases/download/z3-4.8.6/z3-4.8.6-x64-ubuntu-16.04.zip &&
      unzip -j z3-4.8.6-x64-ubuntu-16.04.zip z3-4.8.6-x64-ubuntu-16.04/bin/z3 &&
      mv z3 $HOME/bin/z3 &&
      chmod +x $HOME/bin/z3 &&
      rm -f z3-4.8.6-x64-ubuntu-16.04.zip
    )
  - opam init --auto-setup --disable-sandboxing --comp=4.10.1

install:
  - opam update
  - opam install --yes depext
  - opam depext  --yes frama-c 
  - opam install --yes  alt-ergo
  - travis_wait 15 opam install --yes  coq
  - opam install --yes  why3 why3-coq frama-c
  - eval $(opam env); rm -f $HOME/.why3.conf; why3 config --detect

script:
   - make -C StandardAlgorithms clean
   - make -C StandardAlgorithms test
   - make -C StandardAlgorithms report-clean
   - eval $(opam env); make -C StandardAlgorithms report
   - git diff StandardAlgorithms/Results
