language: c
os:
  - linux
dist: bionic
addons:
  apt:
    packages:
      - astyle
      - aspcud
      - libgnomecanvas2-dev
      - libgtk2.0-dev
      - libgtksourceview2.0-dev
      - cvc4
      - cvc3
      - z3

cache:
  directories:
    - $HOME/bin
    - $HOME/.opam

env:
  global:
    - WP_TIMEOUT=1
    - WP_PROCESSES=3

before_install:
  - sudo apt update -qq
  - which opam || (
      wget --no-clobber https://github.com/ocaml/opam/releases/download/2.0.7/opam-2.0.7-x86_64-linux -O $HOME/bin/opam &&
      chmod +x $HOME/bin/opam
    )
  - opam init --auto-setup --disable-sandboxing --comp=4.09.1

install:
  - opam update
  - opam install --yes depext
  - opam depext  --yes --install frama-c alt-ergo why3
  - rm -f .why3.conf
  - eval $(opam config env); why3 config --detect
  - cat .why3.conf 1>&2 

script:
   - make -C StandardAlgorithms clean
   - make -C StandardAlgorithms test
   - make -C StandardAlgorithms report-clean
